apiVersion: v1
kind: Service
metadata:
  name: movie-app-service
spec:
  type: NodePort   
  selector:
    app: movie-app
  ports:
    - protocol: TCP
      port: 80          # Port inside the cluster
      targetPort: 5000 # Port container is listening on
      nodePort: 30080   # External port on your host
